BISTU_USER=""
BISTU_PASS=""

BISTU_MAC=""

LOGIN_SCHEME="auto"

# LAN_GW="10.144.0.3"
# WLAN_GW="10.144.49.2"
# TEST_URL="http://captive.apple.com/hotspot-detect.html"
# INTERVAL="15"
# RETRY_SEC="5"
# MAX_BACKOFF="120"
